### ISSUE TITLE
doesn't run with tomcat under eclipse

### ISSUE THREAD

**Issue by lumpynose** [bgoodin/BasicWebApp#2]
`Jan 29, 2017 7:55:50 PM org.apache.tomcat.util.digester.SetPropertiesRule begin
WARNING: [SetPropertiesRule]{Server/Service/Engine/Host/Context} Setting property 'source' to 'org.eclipse.jst.jee.server:BasicWebApp' did not find a matching property.
Jan 29, 2017 7:55:50 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server version:        Apache Tomcat/8.5.11
Jan 29, 2017 7:55:50 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server built:          Jan 10 2017 21:02:52 UTC
Jan 29, 2017 7:55:50 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server number:         8.5.11.0
Jan 29, 2017 7:55:50 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: OS Name:               Windows 10
Jan 29, 2017 7:55:50 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: OS Version:            10.0
Jan 29, 2017 7:55:50 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Architecture:          amd64
Jan 29, 2017 7:55:50 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Java Home:             C:\Program Files\Java\jdk1.8.0_121\jre
Jan 29, 2017 7:55:50 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: JVM Version:           1.8.0_121-b13
Jan 29, 2017 7:55:50 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: JVM Vendor:            Oracle Corporation
Jan 29, 2017 7:55:50 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: CATALINA_BASE:         C:\home\rusty\workspaces\stripes\.metadata\.plugins\org.eclipse.wst.server.core\tmp0
Jan 29, 2017 7:55:50 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: CATALINA_HOME:         C:\home\rusty\workspaces\apache-tomcat-8.5.11-windows-x64
Jan 29, 2017 7:55:50 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dcatalina.base=C:\home\rusty\workspaces\stripes\.metadata\.plugins\org.eclipse.wst.server.core\tmp0
Jan 29, 2017 7:55:50 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dcatalina.home=C:\home\rusty\workspaces\apache-tomcat-8.5.11-windows-x64
Jan 29, 2017 7:55:50 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dwtp.deploy=C:\home\rusty\workspaces\stripes\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps
Jan 29, 2017 7:55:50 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Djava.endorsed.dirs=C:\home\rusty\workspaces\apache-tomcat-8.5.11-windows-x64\endorsed
Jan 29, 2017 7:55:50 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dfile.encoding=UTF-8
Jan 29, 2017 7:55:50 PM org.apache.catalina.core.AprLifecycleListener lifecycleEvent
INFO: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: C:\Program Files\Java\jdk1.8.0_121\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:/Program Files/Java/jre1.8.0_121/bin/server;C:/Program Files/Java/jre1.8.0_121/bin;C:/Program Files/Java/jre1.8.0_121/lib/amd64;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\LuxRender;C:\Program Files\LuxRender;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Users\rusty\AppData\Local\Microsoft\WindowsApps;C:\Program Files\eclipse-jee-neon-2-win32-x86_64;;.
Jan 29, 2017 7:55:50 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio-8080"]
Jan 29, 2017 7:55:50 PM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
INFO: Using a shared selector for servlet write/read
Jan 29, 2017 7:55:50 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["ajp-nio-8009"]
Jan 29, 2017 7:55:50 PM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
INFO: Using a shared selector for servlet write/read
Jan 29, 2017 7:55:50 PM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 1192 ms
Jan 29, 2017 7:55:50 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Catalina
Jan 29, 2017 7:55:50 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/8.5.11
Jan 29, 2017 7:55:51 PM org.apache.catalina.util.LifecycleMBeanBase register
WARNING: Failed to register object [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/BasicWebApp-1.1-SNAPSHOT-2017-01-30T03:54:59Z]] with name [Catalina:j2eeType=WebModule,name=//localhost/BasicWebApp-1.1-SNAPSHOT-2017-01-30T03:54:59Z,J2EEApplication=none,J2EEServer=none] during component initialisation
javax.management.MalformedObjectNameException: Invalid character ':' in value part of property
	at javax.management.ObjectName.construct(ObjectName.java:618)
	at javax.management.ObjectName.<init>(ObjectName.java:1382)
	at org.apache.catalina.util.LifecycleMBeanBase.register(LifecycleMBeanBase.java:159)
	at org.apache.catalina.util.LifecycleMBeanBase.initInternal(LifecycleMBeanBase.java:61)
	at org.apache.catalina.core.ContainerBase.initInternal(ContainerBase.java:903)
	at org.apache.catalina.core.StandardContext.initInternal(StandardContext.java:6200)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:140)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Jan 29, 2017 7:55:51 PM org.apache.catalina.util.LifecycleMBeanBase register
WARNING: Failed to register object [org.apache.catalina.webresources.StandardRoot@df0ee6b] with name [Catalina:type=WebResourceRoot,host=localhost,context=/BasicWebApp-1.1-SNAPSHOT-2017-01-30T03:54:59Z] during component initialisation
javax.management.MalformedObjectNameException: Invalid character ':' in value part of property
	at javax.management.ObjectName.construct(ObjectName.java:618)
	at javax.management.ObjectName.<init>(ObjectName.java:1382)
	at org.apache.catalina.util.LifecycleMBeanBase.register(LifecycleMBeanBase.java:159)
	at org.apache.catalina.util.LifecycleMBeanBase.initInternal(LifecycleMBeanBase.java:61)
	at org.apache.catalina.webresources.StandardRoot.initInternal(StandardRoot.java:662)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:140)
	at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:4842)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4974)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Jan 29, 2017 7:55:51 PM org.apache.catalina.util.LifecycleMBeanBase register
WARNING: Failed to register object [org.apache.catalina.webresources.Cache@385b5d6] with name [Catalina:type=WebResourceRoot,host=localhost,context=/BasicWebApp-1.1-SNAPSHOT-2017-01-30T03:54:59Z,name=Cache] during component initialisation
javax.management.MalformedObjectNameException: Invalid character ':' in value part of property
	at javax.management.ObjectName.construct(ObjectName.java:618)
	at javax.management.ObjectName.<init>(ObjectName.java:1382)
	at org.apache.catalina.util.LifecycleMBeanBase.register(LifecycleMBeanBase.java:159)
	at org.apache.catalina.webresources.StandardRoot.initInternal(StandardRoot.java:664)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:140)
	at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:4842)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4974)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Jan 29, 2017 7:55:51 PM org.apache.catalina.core.StandardContext postWorkDirectory
WARNING: Failed to create work directory [C:\home\rusty\workspaces\stripes\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\work\Catalina\localhost\BasicWebApp-1.1-SNAPSHOT-2017-01-30T03:54:59Z] for context [/BasicWebApp-1.1-SNAPSHOT-2017-01-30T03:54:59Z]
Jan 29, 2017 7:55:51 PM org.apache.catalina.util.LifecycleMBeanBase register
WARNING: Failed to register object [WebappLoader[/BasicWebApp-1.1-SNAPSHOT-2017-01-30T03:54:59Z]] with name [Catalina:type=Loader,host=localhost,context=/BasicWebApp-1.1-SNAPSHOT-2017-01-30T03:54:59Z] during component initialisation
javax.management.MalformedObjectNameException: Invalid character ':' in value part of property
	at javax.management.ObjectName.construct(ObjectName.java:618)
	at javax.management.ObjectName.<init>(ObjectName.java:1382)
	at org.apache.catalina.util.LifecycleMBeanBase.register(LifecycleMBeanBase.java:159)
	at org.apache.catalina.util.LifecycleMBeanBase.initInternal(LifecycleMBeanBase.java:61)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:140)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5039)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Jan 29, 2017 7:55:51 PM org.apache.catalina.loader.WebappLoader startInternal
SEVERE: LifecycleException 
javax.management.MalformedObjectNameException: Invalid character ':' in value part of property
	at javax.management.ObjectName.construct(ObjectName.java:618)
	at javax.management.ObjectName.<init>(ObjectName.java:1382)
	at org.apache.catalina.loader.WebappLoader.startInternal(WebappLoader.java:408)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5039)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Jan 29, 2017 7:55:51 PM org.apache.catalina.core.ContainerBase startInternal
SEVERE: A child container failed during start
java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/BasicWebApp-1.1-SNAPSHOT-2017-01-30T03:54:59Z]]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:939)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:872)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/BasicWebApp-1.1-SNAPSHOT-2017-01-30T03:54:59Z]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
	... 6 more
Caused by: org.apache.catalina.LifecycleException: Failed to start component [WebappLoader[/BasicWebApp-1.1-SNAPSHOT-2017-01-30T03:54:59Z]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5039)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 6 more
Caused by: org.apache.catalina.LifecycleException: start: 
	at org.apache.catalina.loader.WebappLoader.startInternal(WebappLoader.java:418)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 8 more
Caused by: javax.management.MalformedObjectNameException: Invalid character ':' in value part of property
	at javax.management.ObjectName.construct(ObjectName.java:618)
	at javax.management.ObjectName.<init>(ObjectName.java:1382)
	at org.apache.catalina.loader.WebappLoader.startInternal(WebappLoader.java:408)
	... 9 more

Jan 29, 2017 7:55:51 PM org.apache.catalina.core.ContainerBase startInternal
SEVERE: A child container failed during start
java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost]]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:939)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:793)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:655)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:355)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:495)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.catalina.LifecycleException: A child container failed during start
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:947)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:872)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 6 more

Jan 29, 2017 7:55:51 PM org.apache.catalina.startup.Catalina start
SEVERE: The required Server component failed to start so Tomcat is unable to start.
org.apache.catalina.LifecycleException: Failed to start component [StandardServer[8005]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:655)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:355)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:495)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardService[Catalina]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:793)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 7 more
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 9 more
Caused by: org.apache.catalina.LifecycleException: A child container failed during start
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:947)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 11 more

Jan 29, 2017 7:55:51 PM org.apache.coyote.AbstractProtocol pause
INFO: Pausing ProtocolHandler ["http-nio-8080"]
Jan 29, 2017 7:55:51 PM org.apache.coyote.AbstractProtocol pause
INFO: Pausing ProtocolHandler ["ajp-nio-8009"]
Jan 29, 2017 7:55:51 PM org.apache.catalina.core.StandardService stopInternal
INFO: Stopping service Catalina
Jan 29, 2017 7:55:51 PM org.apache.coyote.AbstractProtocol destroy
INFO: Destroying ProtocolHandler ["http-nio-8080"]
Jan 29, 2017 7:55:51 PM org.apache.coyote.AbstractProtocol destroy
INFO: Destroying ProtocolHandler ["ajp-nio-8009"]
Jan 29, 2017 7:55:51 PM org.apache.catalina.util.LifecycleMBeanBase register
WARNING: Failed to register object [org.apache.catalina.deploy.NamingResourcesImpl@614ddd49] with name [Catalina:type=NamingResources,host=localhost,context=/BasicWebApp-1.1-SNAPSHOT-2017-01-30T03:54:59Z] during component initialisation
javax.management.MalformedObjectNameException: Invalid character ':' in value part of property
	at javax.management.ObjectName.construct(ObjectName.java:618)
	at javax.management.ObjectName.<init>(ObjectName.java:1382)
	at org.apache.catalina.util.LifecycleMBeanBase.register(LifecycleMBeanBase.java:159)
	at org.apache.catalina.util.LifecycleMBeanBase.initInternal(LifecycleMBeanBase.java:61)
	at org.apache.catalina.deploy.NamingResourcesImpl.initInternal(NamingResourcesImpl.java:932)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
	at org.apache.catalina.core.StandardContext.setNamingResources(StandardContext.java:2010)
	at org.apache.catalina.core.StandardContext.getNamingResources(StandardContext.java:1960)
	at org.apache.catalina.core.NamingContextListener.lifecycleEvent(NamingContextListener.java:217)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:221)
	at org.apache.catalina.util.LifecycleBase.destroy(LifecycleBase.java:264)
	at org.apache.catalina.core.ContainerBase.removeChild(ContainerBase.java:854)
	at org.apache.catalina.core.ContainerBase.destroyInternal(ContainerBase.java:1036)
	at org.apache.catalina.util.LifecycleBase.destroy(LifecycleBase.java:297)
	at org.apache.catalina.core.ContainerBase.removeChild(ContainerBase.java:854)
	at org.apache.catalina.core.ContainerBase.destroyInternal(ContainerBase.java:1036)
	at org.apache.catalina.util.LifecycleBase.destroy(LifecycleBase.java:297)
	at org.apache.catalina.core.StandardService.destroyInternal(StandardService.java:585)
	at org.apache.catalina.util.LifecycleBase.destroy(LifecycleBase.java:297)
	at org.apache.catalina.core.StandardServer.destroyInternal(StandardServer.java:883)
	at org.apache.catalina.util.LifecycleBase.destroy(LifecycleBase.java:297)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:659)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:355)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:495)

Jan 29, 2017 7:55:51 PM org.apache.catalina.loader.WebappLoader stopInternal
SEVERE: LifecycleException 
javax.management.MalformedObjectNameException: Invalid character ':' in value part of property
	at javax.management.ObjectName.construct(ObjectName.java:618)
	at javax.management.ObjectName.<init>(ObjectName.java:1382)
	at org.apache.catalina.loader.WebappLoader.stopInternal(WebappLoader.java:458)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:226)
	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5447)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:226)
	at org.apache.catalina.util.LifecycleBase.destroy(LifecycleBase.java:264)
	at org.apache.catalina.core.ContainerBase.removeChild(ContainerBase.java:854)
	at org.apache.catalina.core.ContainerBase.destroyInternal(ContainerBase.java:1036)
	at org.apache.catalina.util.LifecycleBase.destroy(LifecycleBase.java:297)
	at org.apache.catalina.core.ContainerBase.removeChild(ContainerBase.java:854)
	at org.apache.catalina.core.ContainerBase.destroyInternal(ContainerBase.java:1036)
	at org.apache.catalina.util.LifecycleBase.destroy(LifecycleBase.java:297)
	at org.apache.catalina.core.StandardService.destroyInternal(StandardService.java:585)
	at org.apache.catalina.util.LifecycleBase.destroy(LifecycleBase.java:297)
	at org.apache.catalina.core.StandardServer.destroyInternal(StandardServer.java:883)
	at org.apache.catalina.util.LifecycleBase.destroy(LifecycleBase.java:297)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:659)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:355)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:495)

`

**Comment by bgoodin** [comment]
Feel free to fix it and submit a patch. It works for me :)
